# Generated by Django 5.2.6 on 2025-09-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_tag_spot_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='AI生成'),
        ),
    ]
