# Generated by Django 5.2.6 on 2025-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spot_is_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='画像URL'),
        ),
    ]
