# Generated by Django 5.2.6 on 2025-09-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_spot_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='閲覧日時')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_views', to='spots.spot', verbose_name='スポット')),
            ],
            options={
                'verbose_name': 'スポット閲覧ログ',
                'verbose_name_plural': 'スポット閲覧ログ',
                'indexes': [models.Index(fields=['viewed_at'], name='spots_spotv_viewed__c749f2_idx'), models.Index(fields=['spot', 'viewed_at'], name='spots_spotv_spot_id_01fe26_idx')],
            },
        ),
    ]
