# Generated by ChatGPT

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_spotview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='閲覧回数')),
                (
                    'total_view_duration',
                    models.DurationField(default=datetime.timedelta, verbose_name='累積滞在時間'),
                ),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='最終閲覧日時')),
                (
                    'spot',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='user_interactions',
                        to='spots.spot',
                        verbose_name='スポット',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='spot_interactions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='ユーザー',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ユーザー閲覧データ',
                'verbose_name_plural': 'ユーザー閲覧データ',
                'unique_together': {('user', 'spot')},
            },
        ),
        migrations.AddIndex(
            model_name='userspotinteraction',
            index=models.Index(fields=['user', 'spot'], name='spots_users_user_id_172c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userspotinteraction',
            index=models.Index(fields=['-last_viewed_at'], name='spots_users_last_vi_4d8267_idx'),
        ),
    ]
