# Generated by Django 5.2.6 on 2025-09-27 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0005_spotview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("web_share", "Web Share API"),
                            ("copy_link", "Link Copy"),
                        ],
                        max_length=20,
                        verbose_name="シェア方法",
                    ),
                ),
                ("share_url", models.TextField(blank=True, verbose_name="共有URL")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="ユーザーエージェント"),
                ),
                ("referrer", models.TextField(blank=True, verbose_name="リファラ")),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="共有日時"),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spot_shares",
                        to="spots.spot",
                        verbose_name="スポット",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spot_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="シェアしたユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "スポットシェアログ",
                "verbose_name_plural": "スポットシェアログ",
                "indexes": [
                    models.Index(
                        fields=["shared_at"], name="spots_spots_shared__7b793b_idx"
                    ),
                    models.Index(
                        fields=["spot", "shared_at"],
                        name="spots_spots_spot_id_bc45fa_idx",
                    ),
                    models.Index(
                        fields=["method", "shared_at"],
                        name="spots_spots_method_1afb70_idx",
                    ),
                ],
            },
        ),
    ]
