# Generated by Django 5.2.6 on 2025-09-30 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_recommendationjoblog_recommendationjobsetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='0-100の範囲でAIが算出したスコア', verbose_name='おすすめスコア')),
                ('source', models.CharField(default='api', help_text='api / fallback / manual など', max_length=20, verbose_name='スコア算出元')),
                ('reason', models.TextField(blank=True, help_text='AIが判断した推薦理由(任意)', verbose_name='推薦理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to='spots.spot', verbose_name='スポット')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_scores', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーおすすめスコア',
                'verbose_name_plural': 'ユーザーおすすめスコア',
                'ordering': ['-score', '-updated_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='spots_userr_user_id_6073f9_idx'), models.Index(fields=['updated_at'], name='spots_userr_updated_4b8c23_idx')],
                'unique_together': {('user', 'spot')},
            },
        ),
    ]
