# Generated by Django 4.2.11 on 2025-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_remove_ai_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='閲覧数'),
        ),
    ]
