# Generated by Django 5.2.6 on 2025-11-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_spot_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image_source',
            field=models.CharField(choices=[('uploaded', 'ユーザーアップロード'), ('unsplash', 'Unsplash'), ('wikipedia', 'Wikipedia'), ('other', 'その他'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='画像ソース'),
        ),
    ]
