# Generated by Django 5.2.6 on 2025-12-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0011_spot_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='画像URL'),
        ),
    ]
