# Generated by Django 5.2.6 on 2025-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0013_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image_source',
            field=models.CharField(choices=[('uploaded', 'ユーザーアップロード'), ('unsplash', 'Unsplash'), ('other', 'その他'), ('unknown', '不明')], default='unknown', max_length=20, verbose_name='画像ソース'),
        ),
    ]
