"""
Django settings for travel_log_map project.
Generated by 'django-admin startproject' using Django 5.2.6.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# dj_database_url is only needed for production deployment
try:
    import dj_database_url
except ImportError:
    dj_database_url = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=c9_%nizo8@fm9njwyx)f*_^qd(jv^1@(!613de^98a93*d3=h')

# SECURITY WARNING: don't run with debug turned on in production!
# For local development, default to True if no environment variable is set
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spots',
]

# Add whitenoise.runserver_nostatic for production to disable Django's static file serving
if not DEBUG:
    INSTALLED_APPS.insert(0, 'whitenoise.runserver_nostatic')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add whitenoise middleware only in production
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'travel_log_map.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'travel_log_map.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'DATABASE_URL' in os.environ and dj_database_url:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files configuration
STATICFILES_DIRS = [
    BASE_DIR / 'spots' / 'static',
]

# Use whitenoise storage only in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # WhiteNoise configuration for production
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CSRF settings for external access
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://8000-ij3w7fliisck5f9nvstl9-41315974.manusvm.computer',
    'https://8001-ij3w7fliisck5f9nvstl9-41315974.manusvm.computer',
    'https://*.manusvm.computer',
]


def _env_flag(name: str, default: bool = False) -> bool:
    """環境変数を真偽値として解釈するヘルパー。"""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 't', 'yes', 'on'}


def _env_float(name: str, default: float) -> float:
    """環境変数を浮動小数点として解釈し、失敗したらデフォルト値を返す。"""
    value = os.environ.get(name)
    if value is None:
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


_default_headers = {}
_api_token = os.environ.get('SPOT_API_TOKEN')
if _api_token:
    header_name = os.environ.get('SPOT_API_TOKEN_HEADER', 'Authorization')
    if header_name.lower() == 'authorization' and not _api_token.lower().startswith('bearer '):
        _default_headers[header_name] = f'Bearer {_api_token}'
    else:
        _default_headers[header_name] = _api_token


SPOT_API_CONFIG = {
    'USE_EXTERNAL': _env_flag('SPOT_API_USE_EXTERNAL', False),
    'BASE_URL': (os.environ.get('SPOT_API_BASE_URL') or '').rstrip('/'),
    'TIMEOUT': _env_float('SPOT_API_TIMEOUT', 5.0),
    'HEADERS': _default_headers,
    'ENDPOINTS': {
        'SEARCH': os.environ.get('SPOT_API_SEARCH_PATH', '/api/search/'),
        'LIST': os.environ.get('SPOT_API_LIST_PATH', '/api/spots/'),
        'CREATE': os.environ.get('SPOT_API_CREATE_PATH', '/api/spots/add/'),
    },
}
